version: 2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "requirements.txt" }}'
            - v1-dependencies-
      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          make install
          # Install hadolint
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
      - name: Run lint
        run: |
          . venv/bin/activate
          make lint
  docker:
    runs-on: ubuntu-latest
    container:
      image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "requirements.txt" }}'
            - v1-dependencies-
      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          make install
          # Install hadolint
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
      - name: Run lint
        run: |
          . venv/bin/activate
          make lint
    working-directory: ~/repo